package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sipit
 */
public class FormtblItem extends javax.swing.JPanel {

    /**
     * Creates new form FormtblItem
     */
    public FormtblItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        kodeUsulan2 = new javax.swing.JTextField();
        table = new javax.swing.JPanel();
        inputCepatKey8 = new javax.swing.JButton();
        inputCepatKey11 = new javax.swing.JButton();
        inputCepatKey10 = new javax.swing.JButton();
        inputCepatKey9 = new javax.swing.JButton();

        setBackground(new java.awt.Color(231, 231, 231));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(40, 40, 40));
        jLabel3.setText("Search");

        kodeUsulan2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        kodeUsulan2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        table.setBackground(new java.awt.Color(204, 204, 204));
        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout tableLayout = new javax.swing.GroupLayout(table);
        table.setLayout(tableLayout);
        tableLayout.setHorizontalGroup(
            tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tableLayout.setVerticalGroup(
            tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        inputCepatKey8.setBackground(new java.awt.Color(121, 194, 251));
        inputCepatKey8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputCepatKey8.setForeground(new java.awt.Color(40, 40, 40));
        inputCepatKey8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/find.png"))); // NOI18N
        inputCepatKey8.setText("Find");
        inputCepatKey8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inputCepatKey8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputCepatKey8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inputCepatKey8.setIconTextGap(8);
        inputCepatKey8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCepatKey8ActionPerformed(evt);
            }
        });

        inputCepatKey11.setBackground(new java.awt.Color(121, 194, 251));
        inputCepatKey11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputCepatKey11.setForeground(new java.awt.Color(40, 40, 40));
        inputCepatKey11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/import.png"))); // NOI18N
        inputCepatKey11.setText("Import");
        inputCepatKey11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inputCepatKey11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputCepatKey11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inputCepatKey11.setIconTextGap(20);
        inputCepatKey11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCepatKey11ActionPerformed(evt);
            }
        });

        inputCepatKey10.setBackground(new java.awt.Color(121, 194, 251));
        inputCepatKey10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputCepatKey10.setForeground(new java.awt.Color(40, 40, 40));
        inputCepatKey10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/export.png"))); // NOI18N
        inputCepatKey10.setText("Export");
        inputCepatKey10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inputCepatKey10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputCepatKey10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inputCepatKey10.setIconTextGap(20);
        inputCepatKey10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCepatKey10ActionPerformed(evt);
            }
        });

        inputCepatKey9.setBackground(new java.awt.Color(121, 194, 251));
        inputCepatKey9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputCepatKey9.setForeground(new java.awt.Color(40, 40, 40));
        inputCepatKey9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        inputCepatKey9.setText("Print");
        inputCepatKey9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inputCepatKey9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputCepatKey9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inputCepatKey9.setIconTextGap(23);
        inputCepatKey9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCepatKey9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(inputCepatKey11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(inputCepatKey10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputCepatKey9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kodeUsulan2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputCepatKey8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(456, 456, 456)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kodeUsulan2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCepatKey8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCepatKey11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCepatKey10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCepatKey9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputCepatKey8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCepatKey8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCepatKey8ActionPerformed

    private void inputCepatKey9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCepatKey9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCepatKey9ActionPerformed

    private void inputCepatKey10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCepatKey10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCepatKey10ActionPerformed

    private void inputCepatKey11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCepatKey11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCepatKey11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inputCepatKey10;
    private javax.swing.JButton inputCepatKey11;
    private javax.swing.JButton inputCepatKey8;
    private javax.swing.JButton inputCepatKey9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField kodeUsulan2;
    private javax.swing.JPanel table;
    // End of variables declaration//GEN-END:variables
}
