package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sipit
 */
public class HakAksesPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormHakAkses
     */
    public HakAksesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        gudang = new javax.swing.JCheckBox();
        gudang1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        gudang2 = new javax.swing.JCheckBox();
        gudang3 = new javax.swing.JCheckBox();
        gudang4 = new javax.swing.JCheckBox();
        gudang5 = new javax.swing.JCheckBox();
        gudang6 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        gudang7 = new javax.swing.JCheckBox();
        gudang8 = new javax.swing.JCheckBox();
        gudang9 = new javax.swing.JCheckBox();
        gudang10 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        gudang15 = new javax.swing.JCheckBox();
        gudang16 = new javax.swing.JCheckBox();
        gudang17 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        baruKey1 = new javax.swing.JButton();
        satuan = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(231, 231, 231));
        setName("Hak Akses"); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        jPanel8.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(75, 191, 96));

        jPanel6.setBackground(new java.awt.Color(65, 166, 83));

        jLabel10.setBackground(new java.awt.Color(65, 166, 83));
        jLabel10.setForeground(new java.awt.Color(65, 166, 83));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel10)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setOpaque(false);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hak Akses");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Form ini digunakan untuk membatasi ruang gerak pengguna");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("sesuai Level si pengguna program");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setForeground(new java.awt.Color(40, 40, 40));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(230, 199, 159));
        jPanel2.setOpaque(false);

        gudang.setBackground(new java.awt.Color(230, 199, 159));
        gudang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gudang.setForeground(new java.awt.Color(40, 40, 40));
        gudang.setText("Pengguna");
        gudang.setBorderPaintedFlat(true);
        gudang.setOpaque(false);

        gudang1.setBackground(new java.awt.Color(230, 199, 159));
        gudang1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gudang1.setForeground(new java.awt.Color(40, 40, 40));
        gudang1.setText("Hak Akses");
        gudang1.setBorderPaintedFlat(true);
        gudang1.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gudang1)
                    .addComponent(gudang))
                .addContainerGap(577, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(gudang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gudang1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sistem", jPanel2);

        jPanel3.setBackground(new java.awt.Color(230, 199, 159));
        jPanel3.setToolTipText("");
        jPanel3.setOpaque(false);

        gudang2.setBackground(new java.awt.Color(230, 199, 159));
        gudang2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gudang2.setForeground(new java.awt.Color(40, 40, 40));
        gudang2.setText("Gudang");
        gudang2.setToolTipText("");
        gudang2.setBorderPaintedFlat(true);
        gudang2.setOpaque(false);

        gudang3.setBackground(new java.awt.Color(230, 199, 159));
        gudang3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gudang3.setForeground(new java.awt.Color(40, 40, 40));
        gudang3.setText("Item");
        gudang3.setToolTipText("");
        gudang3.setBorderPaintedFlat(true);
        gudang3.setOpaque(false);
        gudang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gudang3ActionPerformed(evt);
            }
        });

        gudang4.setBackground(new java.awt.Color(230, 199, 159));
        gudang4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gudang4.setForeground(new java.awt.Color(40, 40, 40));
        gudang4.setText("Harga");
        gudang4.setToolTipText("");
        gudang4.setBorderPaintedFlat(true);
        gudang4.setOpaque(false);

        gudang5.setBackground(new java.awt.Color(230, 199, 159));
        gudang5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gudang5.setForeground(new java.awt.Color(40, 40, 40));
        gudang5.setText("Kategori");
        gudang5.setToolTipText("");
        gudang5.setBorderPaintedFlat(true);
        gudang5.setOpaque(false);

        gudang6.setBackground(new java.awt.Color(230, 199, 159));
        gudang6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gudang6.setForeground(new java.awt.Color(40, 40, 40));
        gudang6.setText("Supplier");
        gudang6.setToolTipText("");
        gudang6.setBorderPaintedFlat(true);
        gudang6.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gudang6)
                    .addComponent(gudang5)
                    .addComponent(gudang4)
                    .addComponent(gudang3)
                    .addComponent(gudang2))
                .addContainerGap(547, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(gudang2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gudang3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gudang4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gudang5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gudang6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Master Data", jPanel3);

        jPanel4.setBackground(new java.awt.Color(230, 199, 159));
        jPanel4.setToolTipText("");
        jPanel4.setOpaque(false);

        gudang7.setBackground(new java.awt.Color(230, 199, 159));
        gudang7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gudang7.setForeground(new java.awt.Color(40, 40, 40));
        gudang7.setText("Pembelian");
        gudang7.setToolTipText("");
        gudang7.setBorderPaintedFlat(true);
        gudang7.setOpaque(false);

        gudang8.setBackground(new java.awt.Color(230, 199, 159));
        gudang8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gudang8.setForeground(new java.awt.Color(40, 40, 40));
        gudang8.setText("Penjualan");
        gudang8.setToolTipText("");
        gudang8.setBorderPaintedFlat(true);
        gudang8.setOpaque(false);

        gudang9.setBackground(new java.awt.Color(230, 199, 159));
        gudang9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gudang9.setForeground(new java.awt.Color(40, 40, 40));
        gudang9.setText("Transaksi Gudang");
        gudang9.setToolTipText("");
        gudang9.setBorderPaintedFlat(true);
        gudang9.setOpaque(false);
        gudang9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gudang9ActionPerformed(evt);
            }
        });

        gudang10.setBackground(new java.awt.Color(230, 199, 159));
        gudang10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gudang10.setForeground(new java.awt.Color(40, 40, 40));
        gudang10.setText("Transaksi");
        gudang10.setToolTipText("");
        gudang10.setBorderPaintedFlat(true);
        gudang10.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gudang9)
                    .addComponent(gudang10)
                    .addComponent(gudang8)
                    .addComponent(gudang7))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(gudang7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gudang8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(gudang9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gudang10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transaksi", jPanel4);

        jPanel5.setBackground(new java.awt.Color(230, 199, 159));
        jPanel5.setToolTipText("");
        jPanel5.setOpaque(false);

        gudang15.setBackground(new java.awt.Color(230, 199, 159));
        gudang15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gudang15.setForeground(new java.awt.Color(40, 40, 40));
        gudang15.setText("Gudang");
        gudang15.setToolTipText("");
        gudang15.setBorderPaintedFlat(true);
        gudang15.setOpaque(false);

        gudang16.setBackground(new java.awt.Color(230, 199, 159));
        gudang16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gudang16.setForeground(new java.awt.Color(40, 40, 40));
        gudang16.setText("Pembelian");
        gudang16.setToolTipText("");
        gudang16.setBorderPaintedFlat(true);
        gudang16.setOpaque(false);

        gudang17.setBackground(new java.awt.Color(230, 199, 159));
        gudang17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gudang17.setForeground(new java.awt.Color(40, 40, 40));
        gudang17.setText("Penjualan");
        gudang17.setToolTipText("");
        gudang17.setBorderPaintedFlat(true);
        gudang17.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gudang17)
                    .addComponent(gudang16)
                    .addComponent(gudang15))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(gudang15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gudang16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gudang17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Laporan", jPanel5);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 40, 40));
        jLabel2.setText("Level");

        baruKey1.setBackground(new java.awt.Color(36, 198, 237));
        baruKey1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        baruKey1.setForeground(new java.awt.Color(40, 40, 40));
        baruKey1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/process.png"))); // NOI18N
        baruKey1.setText("Proses");
        baruKey1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        baruKey1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        baruKey1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        baruKey1.setIconTextGap(23);

        satuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        satuan.setForeground(new java.awt.Color(40, 40, 40));
        satuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "            ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        satuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(baruKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baruKey1)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jPanel8, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void gudang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gudang3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gudang3ActionPerformed

    private void gudang9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gudang9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gudang9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baruKey1;
    private javax.swing.JCheckBox gudang;
    private javax.swing.JCheckBox gudang1;
    private javax.swing.JCheckBox gudang10;
    private javax.swing.JCheckBox gudang15;
    private javax.swing.JCheckBox gudang16;
    private javax.swing.JCheckBox gudang17;
    private javax.swing.JCheckBox gudang2;
    private javax.swing.JCheckBox gudang3;
    private javax.swing.JCheckBox gudang4;
    private javax.swing.JCheckBox gudang5;
    private javax.swing.JCheckBox gudang6;
    private javax.swing.JCheckBox gudang7;
    private javax.swing.JCheckBox gudang8;
    private javax.swing.JCheckBox gudang9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox satuan;
    // End of variables declaration//GEN-END:variables
}
