package view;

import control.KategoriControl;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sipit
 */
public class KategoriPanel extends javax.swing.JPanel {

    private KategoriControl kategoriControl = new KategoriControl();

    /**
     * Creates new form FormKategori
     */
    public KategoriPanel() {
        initComponents();
        kategoriControl.refresh(this);
    }

    public JTextField getCariText() {
        return cariText;
    }

    public JTable getDataTable() {
        return dataTable;
    }

    public JComboBox getKategoriComboBox() {
        return kategoriComboBox;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cariText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        inputCepatKey5 = new javax.swing.JButton();
        kategoriComboBox = new javax.swing.JComboBox();

        cariText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cariText.setForeground(new java.awt.Color(40, 40, 40));

        setBackground(new java.awt.Color(231, 231, 231));
        setName("Kategori"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 40, 40));
        jLabel2.setText("Kategori");

        table.setBackground(new java.awt.Color(204, 204, 204));
        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        table.setForeground(new java.awt.Color(40, 40, 40));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Barcode", "Nama", "Satuan", "Dapat Dibeli", "Dapat Dijual", "Dapat Diproduksi", "Untuk Produksi", "Dapat Dibongkar", "Status", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dataTable);

        javax.swing.GroupLayout tableLayout = new javax.swing.GroupLayout(table);
        table.setLayout(tableLayout);
        tableLayout.setHorizontalGroup(
            tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        tableLayout.setVerticalGroup(
            tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        );

        inputCepatKey5.setBackground(new java.awt.Color(36, 198, 237));
        inputCepatKey5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputCepatKey5.setForeground(new java.awt.Color(40, 40, 40));
        inputCepatKey5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/find.png"))); // NOI18N
        inputCepatKey5.setText("Cari");
        inputCepatKey5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inputCepatKey5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputCepatKey5.setIconTextGap(10);
        inputCepatKey5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCepatKey5ActionPerformed(evt);
            }
        });

        kategoriComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stok", "Non Stok" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(kategoriComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inputCepatKey5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputCepatKey5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kategoriComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputCepatKey5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCepatKey5ActionPerformed
        // TODO add your handling code here:
        kategoriControl.populateTable(dataTable, kategoriComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_inputCepatKey5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cariText;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton inputCepatKey5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox kategoriComboBox;
    private javax.swing.JPanel table;
    // End of variables declaration//GEN-END:variables
}
