package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sipit
 */
public class PembelianBarangPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormPembelianBarang
     */
    public PembelianBarangPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jHarga = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ppn = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        inputCepatKey1 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        inputCepatKey = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namaUsulan = new javax.swing.JTextField();
        kodeUsulan = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        tglUsulan = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kodeItem = new javax.swing.JTextField();
        namaItem = new javax.swing.JTextField();
        jPembelian = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        satuan = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        keterangan = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        koseSupplier = new javax.swing.JTextField();
        namaSupplier = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        noTelp = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        cPerson = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tinai = new javax.swing.JCheckBox();
        kredit = new javax.swing.JCheckBox();
        transfer = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        noRek = new javax.swing.JTextField();
        namaBank = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        atasNama = new javax.swing.JTextPane();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        satu = new javax.swing.JCheckBox();
        dua = new javax.swing.JCheckBox();
        tiga = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        gudang = new javax.swing.JCheckBox();
        lokasiLain = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        kodeLokasi = new javax.swing.JTextField();
        kodeGudang = new javax.swing.JTextField();
        namaLokasi = new javax.swing.JTextField();
        tglPenerimaan = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(231, 231, 231));
        setName("Pembelian Barang"); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(40, 40, 40));
        jLabel17.setText("Jumlah Harga");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 362, -1, 29));

        jHarga.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jHarga.setForeground(new java.awt.Color(40, 40, 40));
        jHarga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel8.add(jHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 362, 155, 29));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(40, 40, 40));
        jLabel18.setText("PPN(10%)");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 397, -1, 29));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(40, 40, 40));
        jLabel19.setText("Total");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 432, -1, 29));

        ppn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ppn.setForeground(new java.awt.Color(40, 40, 40));
        ppn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel8.add(ppn, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 397, 155, 29));

        total.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        total.setForeground(new java.awt.Color(40, 40, 40));
        total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel8.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 432, 155, 29));

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(40, 40, 40));
        jLabel33.setText("   :");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 362, -1, 29));

        jLabel34.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(40, 40, 40));
        jLabel34.setText("   :");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 397, -1, 29));

        jLabel35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(40, 40, 40));
        jLabel35.setText("   :");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 432, -1, 29));

        inputCepatKey1.setBackground(new java.awt.Color(36, 198, 237));
        inputCepatKey1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputCepatKey1.setForeground(new java.awt.Color(40, 40, 40));
        inputCepatKey1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/input.png"))); // NOI18N
        inputCepatKey1.setText("Input Cepat");
        inputCepatKey1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inputCepatKey1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputCepatKey1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inputCepatKey1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCepatKey1ActionPerformed(evt);
            }
        });
        jPanel8.add(inputCepatKey1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 46, 115, -1));

        jLabel37.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(40, 40, 40));
        jLabel37.setText("   :");
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 46, -1, 29));

        inputCepatKey.setBackground(new java.awt.Color(36, 198, 237));
        inputCepatKey.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputCepatKey.setForeground(new java.awt.Color(40, 40, 40));
        inputCepatKey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        inputCepatKey.setText("Simpan");
        inputCepatKey.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inputCepatKey.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputCepatKey.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inputCepatKey.setIconTextGap(13);
        inputCepatKey.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jPanel8.add(inputCepatKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 46, 100, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 40, 40));
        jLabel1.setText("Kode Usulan");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 11, -1, 29));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 40, 40));
        jLabel2.setText("Nama Usulan");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 46, -1, 29));

        jLabel38.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(40, 40, 40));
        jLabel38.setText("   :");
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 11, -1, 29));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(40, 40, 40));
        jLabel3.setText("Tanggal");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 18, -1, -1));

        namaUsulan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        namaUsulan.setForeground(new java.awt.Color(40, 40, 40));
        namaUsulan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(namaUsulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 46, 223, 29));

        kodeUsulan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        kodeUsulan.setForeground(new java.awt.Color(40, 40, 40));
        kodeUsulan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(kodeUsulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 11, 223, 29));

        jLabel36.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(40, 40, 40));
        jLabel36.setText("   :");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 11, -1, 29));

        tglUsulan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tglUsulan.setForeground(new java.awt.Color(40, 40, 40));
        tglUsulan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel8.add(tglUsulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 11, 223, 29));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setForeground(new java.awt.Color(40, 40, 40));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(230, 199, 159));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(40, 40, 40));
        jLabel5.setText("Kode Item");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, 29));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(40, 40, 40));
        jLabel6.setText("Nama Item");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 29));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(40, 40, 40));
        jLabel7.setText("Jumlah Pembelian");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, -1, 29));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(40, 40, 40));
        jLabel8.setText("Harga");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, 29));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(40, 40, 40));
        jLabel9.setText("Satuan");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, -1, 29));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(40, 40, 40));
        jLabel10.setText("Keterangan");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        kodeItem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        kodeItem.setForeground(new java.awt.Color(40, 40, 40));
        kodeItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel1.add(kodeItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 14, 150, 29));

        namaItem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        namaItem.setForeground(new java.awt.Color(40, 40, 40));
        namaItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel1.add(namaItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 150, 29));

        jPembelian.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPembelian.setForeground(new java.awt.Color(40, 40, 40));
        jPembelian.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel1.add(jPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 88, 150, 29));

        harga.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        harga.setForeground(new java.awt.Color(40, 40, 40));
        harga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel1.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 125, 150, 29));

        satuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        satuan.setForeground(new java.awt.Color(40, 40, 40));
        satuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "........", "Item 1", "Item 2", "Item 3", "Item 4" }));
        satuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel1.add(satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 165, 131, 29));

        keterangan.setForeground(new java.awt.Color(40, 40, 40));
        jScrollPane1.setViewportView(keterangan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 230, 30));

        jPanel5.setBackground(new java.awt.Color(230, 199, 159));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Supplier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(40, 40, 40))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(40, 40, 40));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(40, 40, 40));
        jLabel11.setText("Kode Supplier");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 36, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(40, 40, 40));
        jLabel12.setText("Nama Supplier");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 76, 101, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(40, 40, 40));
        jLabel13.setText("Alamat");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 116, 72, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(40, 40, 40));
        jLabel14.setText("Nomor Telepon");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 156, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(40, 40, 40));
        jLabel15.setText("Email");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 36, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(40, 40, 40));
        jLabel16.setText("Contact Person");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 76, -1, -1));

        koseSupplier.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        koseSupplier.setForeground(new java.awt.Color(40, 40, 40));
        koseSupplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel5.add(koseSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 150, 29));

        namaSupplier.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        namaSupplier.setForeground(new java.awt.Color(40, 40, 40));
        namaSupplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel5.add(namaSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 150, 29));

        alamat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        alamat.setForeground(new java.awt.Color(40, 40, 40));
        alamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel5.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 150, 29));

        noTelp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        noTelp.setForeground(new java.awt.Color(40, 40, 40));
        noTelp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel5.add(noTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 150, 29));

        email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(40, 40, 40));
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel5.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 30, 150, 29));

        cPerson.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cPerson.setForeground(new java.awt.Color(40, 40, 40));
        cPerson.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel5.add(cPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 70, 150, 29));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(40, 40, 40));
        jLabel27.setText("   :");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 29));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(40, 40, 40));
        jLabel28.setText("   :");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, 29));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(40, 40, 40));
        jLabel29.setText("   :");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 29));

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(40, 40, 40));
        jLabel30.setText("   :");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 70, -1, 29));

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(40, 40, 40));
        jLabel31.setText("   :");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 30, -1, 29));

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(40, 40, 40));
        jLabel32.setText("   :");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 29));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 580, 220));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(40, 40, 40));
        jLabel20.setText("   :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 14, -1, 29));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(40, 40, 40));
        jLabel21.setText("   :");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 29));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(40, 40, 40));
        jLabel22.setText("   :");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 88, -1, 29));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(40, 40, 40));
        jLabel23.setText("   :");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 125, -1, 29));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(40, 40, 40));
        jLabel24.setText("   :");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 165, -1, 29));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(40, 40, 40));
        jLabel26.setText("   :");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, 29));

        jTabbedPane1.addTab("Detail", jPanel1);

        jPanel2.setBackground(new java.awt.Color(230, 199, 159));
        jPanel2.setOpaque(false);

        tinai.setBackground(new java.awt.Color(230, 199, 159));
        tinai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tinai.setForeground(new java.awt.Color(40, 40, 40));
        tinai.setText("Tunai");
        tinai.setBorderPaintedFlat(true);
        tinai.setOpaque(false);

        kredit.setBackground(new java.awt.Color(230, 199, 159));
        kredit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        kredit.setForeground(new java.awt.Color(40, 40, 40));
        kredit.setText("Kredit");
        kredit.setBorderPaintedFlat(true);
        kredit.setOpaque(false);
        kredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreditActionPerformed(evt);
            }
        });

        transfer.setBackground(new java.awt.Color(230, 199, 159));
        transfer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        transfer.setForeground(new java.awt.Color(40, 40, 40));
        transfer.setText("Transfer");
        transfer.setBorderPaintedFlat(true);
        transfer.setOpaque(false);
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(230, 199, 159));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Rekening Bank", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(40, 40, 40))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(40, 40, 40));
        jPanel6.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 40, 40));
        jLabel4.setText("Nomor Rekening");

        jLabel39.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(40, 40, 40));
        jLabel39.setText("Bank");

        jLabel40.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(40, 40, 40));
        jLabel40.setText("Atas Nama");

        noRek.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        noRek.setForeground(new java.awt.Color(40, 40, 40));
        noRek.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));

        namaBank.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        namaBank.setForeground(new java.awt.Color(40, 40, 40));
        namaBank.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));

        jScrollPane2.setForeground(new java.awt.Color(40, 40, 40));

        atasNama.setForeground(new java.awt.Color(40, 40, 40));
        jScrollPane2.setViewportView(atasNama);

        jLabel41.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(40, 40, 40));
        jLabel41.setText("   :");

        jLabel42.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(40, 40, 40));
        jLabel42.setText("   :");

        jLabel43.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(40, 40, 40));
        jLabel43.setText("   :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(noRek)
                    .addComponent(namaBank)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noRek, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaBank, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel40)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jLabel44.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(40, 40, 40));
        jLabel44.setText("Jumlah Uang yang di Bayarkan");

        jTextField19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField19.setForeground(new java.awt.Color(40, 40, 40));
        jTextField19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transfer)
                            .addComponent(kredit)
                            .addComponent(tinai))
                        .addGap(35, 35, 35)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField19)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(tinai, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kredit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pembayaran", jPanel2);

        jPanel3.setBackground(new java.awt.Color(230, 199, 159));
        jPanel3.setOpaque(false);

        satu.setBackground(new java.awt.Color(230, 199, 159));
        satu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        satu.setForeground(new java.awt.Color(40, 40, 40));
        satu.setText("1");
        satu.setBorderPaintedFlat(true);
        satu.setOpaque(false);

        dua.setBackground(new java.awt.Color(230, 199, 159));
        dua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dua.setForeground(new java.awt.Color(40, 40, 40));
        dua.setText("2");
        dua.setBorderPaintedFlat(true);
        dua.setOpaque(false);

        tiga.setBackground(new java.awt.Color(230, 199, 159));
        tiga.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tiga.setForeground(new java.awt.Color(40, 40, 40));
        tiga.setText("3");
        tiga.setBorderPaintedFlat(true);
        tiga.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tiga)
                    .addComponent(dua)
                    .addComponent(satu))
                .addContainerGap(816, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(satu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dua, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tiga, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Persetujuan", jPanel3);

        jPanel4.setBackground(new java.awt.Color(230, 199, 159));
        jPanel4.setOpaque(false);

        gudang.setBackground(new java.awt.Color(230, 199, 159));
        gudang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gudang.setForeground(new java.awt.Color(40, 40, 40));
        gudang.setText("Gudang");
        gudang.setBorderPaintedFlat(true);
        gudang.setOpaque(false);

        lokasiLain.setBackground(new java.awt.Color(230, 199, 159));
        lokasiLain.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lokasiLain.setForeground(new java.awt.Color(40, 40, 40));
        lokasiLain.setText("Lokasi Lian");
        lokasiLain.setBorderPaintedFlat(true);
        lokasiLain.setOpaque(false);

        jPanel7.setBackground(new java.awt.Color(230, 199, 159));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        jPanel7.setForeground(new java.awt.Color(40, 40, 40));
        jPanel7.setOpaque(false);

        jLabel45.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(40, 40, 40));
        jLabel45.setText("Kode Lokasi");

        jLabel46.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(40, 40, 40));
        jLabel46.setText("Kode Gudang");

        jLabel47.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(40, 40, 40));
        jLabel47.setText("Nama Lokasi");

        jLabel48.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(40, 40, 40));
        jLabel48.setText("Tanggal Penerimaan");

        kodeLokasi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        kodeLokasi.setForeground(new java.awt.Color(40, 40, 40));
        kodeLokasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));

        kodeGudang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        kodeGudang.setForeground(new java.awt.Color(40, 40, 40));
        kodeGudang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));

        namaLokasi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        namaLokasi.setForeground(new java.awt.Color(40, 40, 40));
        namaLokasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));

        tglPenerimaan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tglPenerimaan.setForeground(new java.awt.Color(40, 40, 40));
        tglPenerimaan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));

        jLabel49.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(40, 40, 40));
        jLabel49.setText("   :");

        jLabel50.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(40, 40, 40));
        jLabel50.setText("   :");

        jLabel51.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(40, 40, 40));
        jLabel51.setText("   :");

        jLabel52.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(40, 40, 40));
        jLabel52.setText("   :");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kodeLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kodeGudang, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglPenerimaan, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(kodeLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(kodeGudang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(namaLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(tglPenerimaan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lokasiLain)
                    .addComponent(gudang))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(gudang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lokasiLain, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Detail Transfer Barang", jPanel4);

        jPanel8.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 81, -1, -1));

        add(jPanel8, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void kreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kreditActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferActionPerformed

    private void inputCepatKey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCepatKey1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCepatKey1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextPane atasNama;
    private javax.swing.JTextField cPerson;
    private javax.swing.JCheckBox dua;
    private javax.swing.JTextField email;
    private javax.swing.JCheckBox gudang;
    private javax.swing.JTextField harga;
    private javax.swing.JButton inputCepatKey;
    private javax.swing.JButton inputCepatKey1;
    private javax.swing.JTextField jHarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jPembelian;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextPane keterangan;
    private javax.swing.JTextField kodeGudang;
    private javax.swing.JTextField kodeItem;
    private javax.swing.JTextField kodeLokasi;
    private javax.swing.JTextField kodeUsulan;
    private javax.swing.JTextField koseSupplier;
    private javax.swing.JCheckBox kredit;
    private javax.swing.JCheckBox lokasiLain;
    private javax.swing.JTextField namaBank;
    private javax.swing.JTextField namaItem;
    private javax.swing.JTextField namaLokasi;
    private javax.swing.JTextField namaSupplier;
    private javax.swing.JTextField namaUsulan;
    private javax.swing.JTextField noRek;
    private javax.swing.JTextField noTelp;
    private javax.swing.JTextField ppn;
    private javax.swing.JCheckBox satu;
    private javax.swing.JComboBox satuan;
    private javax.swing.JTextField tglPenerimaan;
    private javax.swing.JTextField tglUsulan;
    private javax.swing.JCheckBox tiga;
    private javax.swing.JCheckBox tinai;
    private javax.swing.JTextField total;
    private javax.swing.JCheckBox transfer;
    // End of variables declaration//GEN-END:variables
}
