package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sipit
 */
public class TransferPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormTransfer
     */
    public TransferPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputCepatKey7 = new javax.swing.JButton();
        inputCepatKey8 = new javax.swing.JButton();
        kodeUsulan2 = new javax.swing.JTextField();
        satuan = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputCepatKey10 = new javax.swing.JButton();
        inputCepatKey5 = new javax.swing.JButton();
        inputCepatKey11 = new javax.swing.JButton();
        inputCepatKey9 = new javax.swing.JButton();
        table = new javax.swing.JPanel();

        setBackground(new java.awt.Color(231, 231, 231));
        setName("Transfer"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(231, 231, 231));

        inputCepatKey7.setBackground(new java.awt.Color(36, 198, 237));
        inputCepatKey7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputCepatKey7.setForeground(new java.awt.Color(40, 40, 40));
        inputCepatKey7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/preview.png"))); // NOI18N
        inputCepatKey7.setText("Preview");
        inputCepatKey7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inputCepatKey7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputCepatKey7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inputCepatKey7.setIconTextGap(15);
        inputCepatKey7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCepatKey7ActionPerformed(evt);
            }
        });

        inputCepatKey8.setBackground(new java.awt.Color(36, 198, 237));
        inputCepatKey8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputCepatKey8.setForeground(new java.awt.Color(40, 40, 40));
        inputCepatKey8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/file.png"))); // NOI18N
        inputCepatKey8.setText("Report");
        inputCepatKey8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inputCepatKey8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputCepatKey8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inputCepatKey8.setIconTextGap(20);
        inputCepatKey8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCepatKey8ActionPerformed(evt);
            }
        });

        kodeUsulan2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        kodeUsulan2.setForeground(new java.awt.Color(40, 40, 40));
        kodeUsulan2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        satuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        satuan.setForeground(new java.awt.Color(40, 40, 40));
        satuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "      ", "Item 1", "Item 2", "Item 3", "Item 4" }));
        satuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 40, 40));
        jLabel4.setText("Filter by");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(40, 40, 40));
        jLabel3.setText("Search");

        inputCepatKey10.setBackground(new java.awt.Color(36, 198, 237));
        inputCepatKey10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputCepatKey10.setForeground(new java.awt.Color(40, 40, 40));
        inputCepatKey10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/import.png"))); // NOI18N
        inputCepatKey10.setText("Import");
        inputCepatKey10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inputCepatKey10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputCepatKey10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inputCepatKey10.setIconTextGap(10);
        inputCepatKey10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCepatKey10ActionPerformed(evt);
            }
        });

        inputCepatKey5.setBackground(new java.awt.Color(36, 198, 237));
        inputCepatKey5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputCepatKey5.setForeground(new java.awt.Color(40, 40, 40));
        inputCepatKey5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        inputCepatKey5.setText("Find");
        inputCepatKey5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inputCepatKey5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCepatKey5ActionPerformed(evt);
            }
        });

        inputCepatKey11.setBackground(new java.awt.Color(36, 198, 237));
        inputCepatKey11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputCepatKey11.setForeground(new java.awt.Color(40, 40, 40));
        inputCepatKey11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/export.png"))); // NOI18N
        inputCepatKey11.setText("Export");
        inputCepatKey11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inputCepatKey11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputCepatKey11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inputCepatKey11.setIconTextGap(20);
        inputCepatKey11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCepatKey11ActionPerformed(evt);
            }
        });

        inputCepatKey9.setBackground(new java.awt.Color(36, 198, 237));
        inputCepatKey9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputCepatKey9.setForeground(new java.awt.Color(40, 40, 40));
        inputCepatKey9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transfer.png"))); // NOI18N
        inputCepatKey9.setText("New Transfer");
        inputCepatKey9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inputCepatKey9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCepatKey9ActionPerformed(evt);
            }
        });

        table.setBackground(new java.awt.Color(204, 204, 204));
        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 40, 40)));
        table.setForeground(new java.awt.Color(40, 40, 40));

        javax.swing.GroupLayout tableLayout = new javax.swing.GroupLayout(table);
        table.setLayout(tableLayout);
        tableLayout.setHorizontalGroup(
            tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );
        tableLayout.setVerticalGroup(
            tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(satuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kodeUsulan2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputCepatKey5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inputCepatKey7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputCepatKey10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inputCepatKey8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputCepatKey11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inputCepatKey9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kodeUsulan2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCepatKey7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCepatKey10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCepatKey5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCepatKey8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(inputCepatKey11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputCepatKey9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputCepatKey7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCepatKey7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCepatKey7ActionPerformed

    private void inputCepatKey8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCepatKey8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCepatKey8ActionPerformed

    private void inputCepatKey9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCepatKey9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCepatKey9ActionPerformed

    private void inputCepatKey10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCepatKey10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCepatKey10ActionPerformed

    private void inputCepatKey5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCepatKey5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCepatKey5ActionPerformed

    private void inputCepatKey11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCepatKey11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCepatKey11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inputCepatKey10;
    private javax.swing.JButton inputCepatKey11;
    private javax.swing.JButton inputCepatKey5;
    private javax.swing.JButton inputCepatKey7;
    private javax.swing.JButton inputCepatKey8;
    private javax.swing.JButton inputCepatKey9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kodeUsulan2;
    private javax.swing.JComboBox satuan;
    private javax.swing.JPanel table;
    // End of variables declaration//GEN-END:variables
}
